.card {
  width: 184px;
  display: inline-block;
  margin: 12px;
  text-align: left;
  cursor: pointer;
  vertical-align: top;
  /* background: #2a2a2f; */
  border-radius: 0;
  overflow: hidden;
}

.card:hover {
  /*  background: #42424A; */
}

.card .title {
  margin: 12px 8px 4px 8px;
  font-size: 0.78em;
  font-weight: bold;
  overflow: hidden;
  display: -webkit-box;
  line-height: 1.3;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

.card .subtitle {
  margin: 0 8px 12px 8px;
  opacity: 0.5;
  width: 80%;
  font-size: 0.7em;
  font-weight: bold;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
  text-transform: uppercase;
}

.placeholder .title {
  width: 64%;
  opacity: 0.25;
  margin: 8px 8px;
  margin-top: 16px;
  height: 0.74em;
  border-radius: 1em;
  background: #fff;
}

.placeholder .subtitle {
  width: 35%;
  height: 0.7em;
  opacity: 0.1;
  margin: 8px 8px;
  margin-bottom: 16px;
  border-radius: 1em;
  background: #fff;
}

.tags {
  margin: 8px 0 0 0;
}

.tag {
  display: inline-block;
  padding: 4px 8px;
  margin-right: 8px;
  margin-bottom: 8px;
  background: #414759;
  border-radius: 4px;
  font-size: 0.8em;
}

.actions {
  display: flex;
  justify-content: flex-start;
  align-items: center;
  padding: 2px 0px;
}
