.player {
  position: fixed;
  margin: auto;
  bottom: 0;
  left: 0;
  right: 0;
  height: var(--player-height);
  border-top: 1px solid var(--border-color);
  display: inline-block;
  background: var(--sidebar-bg-color);
  transform: translateY(100%);
  transition: transform 300ms ease;
  will-change: transform;
  z-index: 1;
}

.player.active {
  transform: translateY(0%);
}

.player .container {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: space-between;
  margin: 0;
  vertical-align: center;
  align-self: center;
  height: 100%;
}

.player .controls {
  width: 100%;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: space-around;
  margin: 0;
}

.player .actions {
  margin: 0 16px;
  display: inline-block;
  flex-shrink: 0;
}

.player .seek {
  margin: 12px 0;
  flex-grow: 1;
}

.player .seekBar {
  display: flex;
  align-items: center;
  align-self: center;
  align-content: center;
  width: 100%;
}

.player .seekBar .currentTime {
  margin-right: 16px;
  opacity: 0.64;
}

.player .seekBar .duration {
  margin-left: 16px;
  opacity: 0.64;
}

.player audio {
  display: none;
}

/* Button */

.button {
  border: 0;
  background: transparent;
  display: inline-block;
  color: inherit;
  font-size: 1em;
  padding: 4px;
  margin: 0 4px;
  border-radius: 50%;
  transition: background 0.3s ease;
}

.button svg {
  display: inline-block;
  vertical-align: middle;
  margin: auto;
}

.button:hover:not(:disabled) {
  opacity: 0.9;
  background: rgba(255, 255, 255, 0.15);
}

.button:active {
  opacity: 1;
}

.button:disabled {
  opacity: 0.24;
  cursor: default;
}

/* Stack */

.stack {
  display: flex;
  align-items: center;
  align-content: center;
  padding: 0px;
  margin: 0;
  flex-shrink: 1;
  flex-grow: 0;
  height: 100%;
  width: var(--sidebar-width);
  box-sizing: border-box;
  text-align: left;
}

.stack:hover {
}

.stack:hover .stackLabel {
  opacity: 1;
}

.stackLabel {
  margin: 0;
  margin-left: 16px;
  font-size: 0.86em;
  font-weight: 600;
}
.stackLabel p {
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
  margin: 2px 0;
}
.stackLabel .artist {
  opacity: 0.64;
}

.labelLink {
  cursor: pointer;
}

.labelLink:hover {
  text-decoration: underline;
}

.stackThumb {
  flex-shrink: 0;
  height: 40px;
  width: 40px;
  margin-left: 16px;
  border-radius: 4px;
  background-color: rgba(255, 255, 255, 0.4);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Metadata */

.trackData {
  flex-grow: 1;
  margin: 0 8px;
  padding: 0 8px;
  position: relative;
  text-align: center;
}

.trackData p {
  width: 100%;
  margin: 0;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
}

.trackData .trackArtist {
  opacity: 0.64;
  cursor: pointer;
}

.trackData .trackArtist:hover {
  text-decoration: underline;
}

.trackData .divider {
  opacity: 0.4;
  margin: 0 8px;
  font-weight: 600;
}
