.player {
  position: fixed;
  margin: auto;
  bottom: 0;
  left: 0;
  right: 0;
  height: var(--player-height);
  border-top: 1px solid var(--bg-color);
  display: inline-block;
  background: var(--card-bg-color);
  transform: translateY(100%);
  transition: transform 300ms ease;
  will-change: transform;
  z-index: 1;
}

.player.active {
  transform: translateY(0%);
}

.player .container {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: space-between;
  margin: 0;
  vertical-align: center;
  align-self: center;
  height: 100%;
}

.player .controls {
  width: 100%;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: space-around;
  margin: 0;
}

.player .actions {
  margin: 0 16px;
  display: inline-block;
  flex-shrink: 0;
}

.player .seek {
  margin: 12px 0;
}

.player audio {
  display: none;
}

/* Button */

.button {
  border: 0;
  background: transparent;
  display: inline-block;
  color: inherit;
  font-size: 1em;
  padding: 4px;
  margin: 0 4px;
  border-radius: 50%;
  transition: background 0.3s ease;
}

.button svg {
  display: inline-block;
  vertical-align: middle;
  margin: auto;
}

.button:hover:not(:disabled) {
  opacity: 0.9;
  background: rgba(255, 255, 255, 0.15);
}

.button:active {
  opacity: 1;
}

.button:disabled {
  opacity: 0.4;
  cursor: default;
}

/* Stack */

.stack {
  display: flex;
  align-items: center;
  align-content: center;
  padding: 8px;
  margin: 0 8px;
  flex-shrink: 1;
  flex-grow: 0;
  border-radius: 4px;
}

.stack:hover {
  background: var(--button-bg-color);
}

.stack:hover .stackLabel {
  opacity: 1;
}

.stackLabel {
  display: inline-block;
  margin: 0 16px;
  font-size: 0.96em;
  font-weight: 600;
  opacity: 0.64;
}

.stackThumb {
  flex-shrink: 0;
  height: 36px;
  width: 36px;
  margin: 0;
  border-radius: 4px;
  background-color: rgba(255, 255, 255, 0.4);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Metadata */

.trackData {
  flex-grow: 1;
  margin: 0 8px;
  padding: 0 8px;
  position: relative;
  text-align: left;
  overflow: hidden;
}

.trackData p {
  width: 100%;
  overflow: hidden;
  white-space: nowrap;
  display: inline;
  margin: 0;
}

.trackData .trackArtist {
  opacity: 0.64;
}

.trackData .divider {
  opacity: 0.4;
  margin: 0 8px;
  font-weight: 600;
}
