.player {
  bottom: 0;
  left: 0;
  right: 0;
  position: fixed;
  margin: auto;
  z-index: 99;
  display: inline-block;
  background: rgba(44, 46, 52, 0.99);
  padding-top: 4px;
  transform: translateY(100%);
}

.player.active {
  animation-name: show;
  animation-duration: 0.3s;
  animation-delay: 0.3s;
  animation-fill-mode: forwards;
  animation-timing-function: ease;
}

.player .container {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: space-between;
  width: 100%;
  margin: 0;
}

.player .controls {
  flex-grow: 1;
  text-align: center;
}

.player .actions {
  flex-grow: 1;
  flex-basis: 0;
  text-align: right;
  padding-right: 16px;
}

.player .seek{
  margin: 0 auto;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}

.player audio {
  display: none;
}


/* Button */

.button {
  border: 0;
  background: transparent;
  display: inline-block;
  color: inherit;
  font-size: 1.3em;
  padding: 6px;
  margin: 0 8px;
  opacity: 0.9;
  border-radius: 8px;
  transition: background 0.3s ease;
}

.button:hover:not(:disabled) {
  opacity: 0.9;
  background: rgba(255,255,255, 0.15);
}

.button:active {
  opacity: 1;
}

.button:disabled {
  opacity: 0.4;
}

/* Metadata */

.card  {
  display: flex;
  flex-grow: 1;
  flex-basis: 0;
  align-items: center;
  align-content: center;
  padding-right: 16px;
}

.trackInfo {
  display: inline-block;
  margin-left: 16px;
  font-size: 0.8em;
  flex-shrink: 2;
  display: flex;
  min-width: 0;
  flex-direction: column;
}

.trackInfo p{
  margin: 2px 0;
  line-height: 1.2;
  font-weight:bolder;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

.trackInfo .author {
  flex-grow: 0;
  opacity: 0.6;
}

.thumbnail {
  flex-shrink: 0;
  height: 64px;
  width: 64px;
  background: rgba(255, 255, 255, 0.5);
  margin: 0;
  background-color: #282c37;
  background-position: center;
  background-repeat:no-repeat;
  background-size:contain;
}

@keyframes show {
  from {
    transform: translateY(100%);
  }
  to {
    transform: translateY(0%);
  }
}
