.thumb {
    height: 164px;
    width: 164px;
    margin: 16px 0;
    background-color: #282c37;
    background-position: center;
    background-repeat:no-repeat;
    background-size:contain;
    position: relative;
    overflow: hidden;
    padding: 4px;
}

.overlay {
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
    margin: auto;
    background-color: #282c37;
    transition: opacity 0.3s ease;
    transition-delay: 0.3s;
}
