.thumb {
  height: 184px;
  width: 100%;
  overflow: hidden;
  position: relative;
  margin: 0;
  opacity: 0;
  transition: opacity 0.3s ease 0.3s;
}

.thumb img,
.thumbReady img {
  display: none;
}

.thumbReady {
  composes: thumb;
  opacity: 1;
}

.picture {
  height: 100%;
  width: 100%;
  background-color: rgba(0, 0, 0, 0.2);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  z-index: 1;
  filter: blur(0px);
}

.overlay:hover {
  opacity: 1;
}

.overlay {
  width: 100%;
  height: 100%;
  opacity: 0;
  position: absolute;
  top: 0;
  left: 0;
  margin: auto;

  background: rgba(18, 18, 20, 0.75);

  background: -webkit-linear-gradient(
    top,
    rgba(18, 18, 20, 0) 0%,
    rgba(18, 18, 20, 0.9) 100%
  );

  background: linear-gradient(
    to bottom,
    rgba(18, 18, 20, 0) 0%,
    rgba(18, 18, 20, 0.9) 100%
  );

  transition: all 0.3s ease;
}

.metadata {
  padding: 16px;
  position: absolute;
  bottom: 0;
  left: 0;
}
