.view {
  margin: 0 auto;
  padding: 64px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  align-content: center;
  animation-name: show;
  animation-duration: 0.3s;
  animation-delay: 0.3s;
  animation-fill-mode: both;
  animation-timing-function: ease;
  overflow: hidden;
  position: relative;
}

.backdrop {
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  z-index: -2;
  opacity: 0.2;
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  filter: blur(8px);
  transform: scale(1.1);
  margin: auto;
}

.view h1 {
  margin: 16px;
  padding: 8px;
}

.view h3 {
  margin: 16px;
  padding: 8px;
  opacity: 0.75;
  font-weight: normal;
}

.thumbnail {
  height: 250px;
  width: 250px;
  flex-shrink: 0;
  margin: 16px;
  background-color: #555;
  background-position: center;
  background-repeat: no-repeat;
  background-size: contain;
}

.metadata {
  margin-bottom: 32px;
  text-align: left;
}

.metadata h1,
h2,
p {
  margin: 8px 0;
  padding: 0;
}

.metadata h1 {
  font-size: 1.4em;
}

.metadata h2 {
  opacity: 0.7;
  font-size: 1em;
  text-transform: uppercase;
}

.container {
  display: flex;
  align-content: center;
  justify-content: space-between;
}

.box {
  margin: 16px;
}

@keyframes show {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
